<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion>
    <groupId>com.reactor</groupId><artifactId>rust-java-starter-dubbo</artifactId><version>4.3.0</version>
    <properties><maven.compiler.release>21</maven.compiler.release><project.build.sourceEncoding>UTF-8</project.build.sourceEncoding></properties>
    <dependencies>
        <dependency><groupId>com.reactor</groupId><artifactId>rust-java-starter-rest</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.reactor</groupId><artifactId>java-rust-dubbo</artifactId><version>0.7.1</version><classifier>native-static</classifier></dependency>
    </dependencies>
</project>
